# Generated by Django 2.1.5 on 2019-12-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30)),
                ('class_name', models.IntegerField()),
                ('class_letter', models.TextField(blank=True, max_length=2)),
                ('date', models.DateField()),
            ],
        ),
    ]
